### ISSUE TITLE
Some pat files did not download completely

### ISSUE THREAD

**Issue by 007revad** [stopforumspam/download-synology-dsm#1]
I was using your excellent script today to update my archive of DSM pat files when I noticed a few of the downloaded pat files are 0 bytes.

I though it's easy enough to search for 0 bytes files, delete them, then run the script again. But then I noticed a couple that are larger than zero bytes but obviously not the correct size. Like 960 KB and 6,656 KB. So I thought, no problem, I'll just check the log for errors... but there are no errors logged. I ran the script from a shell with `php ./clone.php >./clone.log`

Now I'm concerned that I can't tell which downloads failed and which ones were successful. 

Would it be easy for you to update the script to check the file size and resume the download if the size is smaller than the size on Synology's server?

**Comment by stopforumspam** [comment]
i added a quick and dirty check that will delete a local file that doesn't match the remote file size, so that it will download again

**Comment by 007revad** [comment]
Thank you.

It's working well, reloading the incomplete files (after I edited the script).

It was downloading every .pat file again, except it was saving them to "downloads/Os/DSM/" instead of "downloads/Os/DSM/7.2.1-69057-1/" etc.

```
# php ./clone.php 2>&1 | tee ./clone.log
DIR: /download/Os/DSM/7.2.1-69057-1
Downloading: download/Os/DSM/synology_alpine4k_ds416.pat
Downloading: download/Os/DSM/synology_alpine_ds1517.pat
Downloading: download/Os/DSM/synology_alpine_ds1817.pat
Downloading: download/Os/DSM/synology_apollolake_1019+.pat
```

To get it to download the .pat files to their correct folders I had to change 3 lines.

Line 2:
- from `function getLinks($url) {`
- to `function getLinks($url, $dir) {`

Line 15:
- from `$path = "download/Os/DSM/"`
- to `$path = "download/Os/DSM/$dir/";`

Line 53:
- from `getLinks("https://archive.synology.com/download/Os/DSM");`
- to `getLinks("https://archive.synology.com/download/Os/DSM" , "");`

**Comment by stopforumspam** [comment]
ah, ok, let me fix that, my bad

**Comment by stopforumspam** [comment]
try that, sorry, I was doing in on a machine with limited path size so that wasnt intended

**Comment by 007revad** [comment]
Thank you.

It's working perfectly now.

Your script downloaded every .pat file for 6.2.4-25556 and 7.0.1-42218 even though I had downloaded those .pat files in late January. I figured out the script was working as it should, and that Synology have quietly updated those .pat files in early Feb and May. They probably include Update 1 now.

**Comment by stopforumspam** [comment]
I think they removed a codec that they no longer had a license for

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 007revad** [comment]
> I think they removed a codec that they no longer had a license for

You're correct. I unpacked of couple of the 6.2.4-25556 .pat files and they are "6.2.4-25556 (with Update 7)"
